sudo: required
language: rust
rust: stable
install:
  - wget https://github.com/rust-lang-nursery/mdBook/releases/download/v0.1.8/mdbook-v0.1.8-i686-unknown-linux-gnu.tar.gz
  - tar -xzf mdbook-v0.1.8-i686-unknown-linux-gnu.tar.gz
  - sudo pip install awscli
script:
  - ./mdbook build
  # If the build is not a PR and is on the source branch, deploy the GitBook to S3.
  # CLI cloudfront invalidation is still in preview: http://docs.aws.amazon.com/cli/latest/reference/cloudfront/create-invalidation.html
  - | 
      if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "source" ]]; then
        aws s3 sync --acl public-read --delete book/ s3://rusoto.org ;
        aws configure set preview.cloudfront true ;
        aws cloudfront create-invalidation --distribution-id E1LZO76WJHQFTB --paths "/*";
      else
        echo "conditions not right for publish"
      fi

branches:
  only:
    - source
    - auto
notifications:
  email: false
