[package]
name = "rusoto_docs_tester"
version = "0.1.0"
authors = ["Matthew Mayer <matthewkmayer@gmail.com>"]
build = "build.rs"

[dependencies]
rusoto_core = "0.41"
rusoto_ecs = "0.41"
rusoto_dynamodb = "0.41"
rusoto_s3 = "0.41"
env_logger = "0.5"
tokio-core = "0.1"
futures = "0.1"

[build-dependencies]
skeptic = "0.13"

[dev-dependencies]
skeptic = "0.13"
